import React from 'react';
import { useAuth } from '../utils/AuthContext';

// Single source of truth for the "Generated by ... on ..." line every
// printed document must carry. Reads the logged-in user itself so every
// call site just needs to drop <PrintFooter /> in — no props to wire up,
// no risk of one document's copy drifting from another's.
export default function PrintFooter() {
  const { user } = useAuth();
  const now = new Date();
  const dd = String(now.getDate()).padStart(2, '0');
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const yyyy = now.getFullYear();
  let hh = now.getHours();
  const min = String(now.getMinutes()).padStart(2, '0');
  const ampm = hh >= 12 ? 'PM' : 'AM';
  hh = hh % 12; if (hh === 0) hh = 12;
  const stamp = `${dd}-${mm}-${yyyy} ${String(hh).padStart(2, '0')}:${min} ${ampm}`;

  return (
    <p className="hidden print:block text-[9px] text-gray-400 mt-3 text-right">
      Generated by: {user?.username || 'system'} &middot; {stamp}
    </p>
  );
}
